### ISSUE TITLE
I tried to implement pmax in Javascript, But the result is not as expected could you please check the code for me

### ISSUE THREAD

**Issue by rishikesh2003** [ttufekci/pmax#1]
`const ATR = require("technicalindicators").ATR;
const EMA = require("technicalindicators").EMA;

const PMAX = (high, low, close) => {
  const ATRperiod = 10;
  const EMAPeriod = 10;
  const ATRMultiplier = 3;

  const ATRInput = {
    high: high,
    low: low,
    close: close,
    period: ATRperiod,
  };
  const EMAInput = high.map((highPrice, idx) => {
    return (highPrice + low[idx]) / 2;
  });

  const ATRarr = ATR.calculate(ATRInput);
  const EMAarr = EMA.calculate({
    period: EMAPeriod,
    values: EMAInput,
  });

  // pmax calculation starts

  const generatePMAX = () => {
    let previousFinalUpperBand = 0;
    let previousFinalLowerBand = 0;
    let finalUpperBand = 0;
    let finalLowerBand = 0;
    let previousEMA = 0;
    let previousPMAX = 0;
    let PMAXArr = [];
    let pmaxc = 0;
    for (let i = 0; i < close.length; i++) {
      let atrc = ATRarr[i];
      let emac = EMAarr[i];
      let basicUpperBand = emac + ATRMultiplier * atrc;
      let basicLowerBand = emac - ATRMultiplier * atrc;
      if (
        basicUpperBand < previousFinalUpperBand ||
        previousEMA > previousFinalUpperBand
      ) {
        finalUpperBand = basicUpperBand;
      } else {
        finalUpperBand = previousFinalUpperBand;
      }
      if (
        basicLowerBand > previousFinalLowerBand ||
        previousEMA < previousFinalLowerBand
      ) {
        finalLowerBand = basicLowerBand;
      } else {
        finalLowerBand = previousFinalLowerBand;
      }
      if (previousPMAX === previousFinalUpperBand && emac <= finalUpperBand) {
        pmaxc = finalUpperBand;
      } else {
        if (previousPMAX === previousFinalUpperBand && emac >= finalUpperBand) {
          pmaxc = finalLowerBand;
        } else {
          if (
            previousPMAX === previousFinalLowerBand &&
            emac >= finalLowerBand
          ) {
            pmaxc = finalLowerBand;
          } else if (
            previousPMAX === previousFinalLowerBand &&
            emac <= finalLowerBand
          ) {
            pmaxc = finalUpperBand;
          }
        }
      }
      PMAXArr.push(pmaxc);
      previousEMA = emac;
      previousFinalUpperBand = finalUpperBand;
      previousFinalLowerBand = finalLowerBand;
      previousPMAX = pmaxc;
    }
    return PMAXArr;
  };
  const PMAXArr = generatePMAX();
  let lastEMA = EMAarr[EMAarr.length - 1];
  let previousEMA = EMAarr[EMAarr.length - 2];
  let lastPMAX = PMAXArr[PMAXArr.length - 1];
  let previousPMAX = PMAXArr[PMAXArr.length - 2];
  console.log(lastEMA, lastPMAX, previousEMA, previousPMAX);
  if (lastEMA > lastPMAX && previousEMA < previousPMAX) {
    console.log("BUY");
  }
  if (lastEMA < lastPMAX && previousEMA > previousPMAX) {
    console.log("SELL");
  }
};

`

**Comment by rkeshs** [comment]
Help Wanted!
